In [2]:
import numpy as np

arr_1_d = np.asarray([1]) # 浅拷贝
print(arr_1_d)

arr_2_d = np.array([[1,2], [3,4]])  # 深拷贝
print(arr_2_d)

[1]
[[1 2]
 [3 4]]


#### ndim 数组维度，轴的个数

In [3]:
arr_1_d.ndim, arr_2_d.ndim

(1, 2)

#### shape 数组维度或者形状，一个整数元组

In [4]:
arr_1_d.shape, arr_2_d.shape

((1,), (2, 2))

In [5]:
# 将 arr_2_d 转为 4行1列
arr_2_d.reshape((4,1))

array([[1],
       [2],
       [3],
       [4]])

##### reshape 用法
`np.reshape(a, newshape, order)`
- a: 要变换的数组
- newshape: 新的形状
- order: 'C'行优先(默认) 'F'列优先 'A'按照原数组的来

即，按照指定的方式 C or F 将数组展开，再用指定方式写到新数组中

#### size 数组元素的总数 也是 shape(a,b) 中的 a*b

In [6]:
arr_2_d.size

4

#### dtype 数组元素类型的对象

In [7]:
arr_2_d.dtype

dtype('int32')

In [8]:
arr_2_d = np.array([[1,2], [3,4]], dtype='float')
arr_2_d.dtype

dtype('float64')

##### astype() 改变数组元素数据类型 不改变原来数组，会在原基础上创建新的数组

In [10]:
new_arr_2_d = arr_2_d.astype('int32')
new_arr_2_d.dtype

dtype('int32')

#### 其他数组创建方式

In [11]:
ones = np.ones(shape=(2,3), dtype='int32')    # 必须传入数组形状
zeros = np.zeros(shape=(3,3))

a5 = np.arange(5)
a_2_to_4 = np.arange(2, 5)
a_2_to_8_k3 = np.arange(2, 9, 3)

print(ones)
print(zeros)
print(a5)
print(a_2_to_4)
print(a_2_to_8_k3)

# 等差数列
# np.linspace(start必选, stop必选, num=50个数默认50, endpoint=True True最后一个元素是stop, retstep=False是否返回公差, dtype=None)
np.linspace()

[[1 1 1]
 [1 1 1]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[0 1 2 3 4]
[2 3 4]
[2 5 8]


#### 数组的轴
0 轴 Y 方向
1 轴 X 方向

In [13]:
m = np.array([
    [4,7,5],
    [4,2,5],
    [7,2,4],
    [1,2,4]])
np.sum(m, axis=0), np.sum(m, axis=1)

(array([16, 13, 18]), array([16, 11, 13,  7]))