In [3]:
import torch

In [4]:
A = torch.ones(3,3)
B = 2 * torch.ones(3,3)
A

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [5]:
B

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])

In [6]:
# tensor 拼接
C = torch.cat((A, B), dim=0)
C

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])

In [7]:
D = torch.cat((A, B), dim=1)
D

tensor([[1., 1., 1., 2., 2., 2.],
        [1., 1., 1., 2., 2., 2.],
        [1., 1., 1., 2., 2., 2.]])

In [8]:
# tensor 维度增加
A = torch.arange(0, 4)
A

tensor([0, 1, 2, 3])

In [9]:
B = torch.arange(5, 9)
B

tensor([5, 6, 7, 8])

In [10]:
C = torch.stack((A, B), dim=0)  # dim = 0 行维度 1 列维度
C

tensor([[0, 1, 2, 3],
        [5, 6, 7, 8]])

In [11]:
# Tensor 切分 安装切完的份数
A = torch.tensor([1,2,3,4,5,6,7,8,9,10])
B = torch.chunk(A, 2, dim=0)    # 切两组 沿着 第0轴方向
B

(tensor([1, 2, 3, 4, 5]), tensor([ 6,  7,  8,  9, 10]))

In [12]:
A = torch.ones(4,4)
A

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [13]:
B = torch.chunk(A, 2, 0)
B

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.]]))

In [14]:
# Tensor切分 按照每份的大小
A = torch.rand(4,4)
A

tensor([[0.5277, 0.5972, 0.3884, 0.7559],
        [0.0956, 0.4197, 0.2194, 0.4995],
        [0.7149, 0.9375, 0.0746, 0.4191],
        [0.8098, 0.2248, 0.2067, 0.2384]])

In [15]:
B = torch.split(A, 2, 0)
B

(tensor([[0.5277, 0.5972, 0.3884, 0.7559],
         [0.0956, 0.4197, 0.2194, 0.4995]]),
 tensor([[0.7149, 0.9375, 0.0746, 0.4191],
         [0.8098, 0.2248, 0.2067, 0.2384]]))

In [16]:
# unbind 函数
A = torch.arange(0, 16).view(4, 4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])

In [17]:
b = torch.unbind(A, dim=0)  # 直接按照某个维度切分
b

(tensor([0, 1, 2, 3]),
 tensor([4, 5, 6, 7]),
 tensor([ 8,  9, 10, 11]),
 tensor([12, 13, 14, 15]))

In [18]:
# 选择tensor的某维数据 基于索引选择某些数据
A = torch.arange(0, 16).view(4, 4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])

In [19]:
B = torch.index_select(A, 0, torch.tensor([1,3]))
B

tensor([[ 4,  5,  6,  7],
        [12, 13, 14, 15]])

In [20]:
# 基于某些判断条件选择
A  = torch.rand(5)
A

tensor([0.9475, 0.0332, 0.6417, 0.4984, 0.9289])

In [21]:
B = A > 0.3
B

tensor([ True, False,  True,  True,  True])

In [22]:
C = torch.masked_select(A, B)
C

tensor([0.9475, 0.6417, 0.4984, 0.9289])

In [23]:
# 综合
A = torch.rand(5)
C = torch.masked_select(A, A>0.3)
C

tensor([0.5359, 0.4625, 0.4735, 0.5156])

In [31]:
# 小练习
A = torch.tensor([[4,5,7], [3,9,8], [2,3,4]])
A
# 取出 第一行第一个 
a11 = torch.index_select(torch.index_select(A, 0, torch.tensor([0])), 1, torch.tensor([0]))
print(a11)
# 第二行第一个和第二个
a21 = torch.index_select(torch.index_select(A, 0, torch.tensor([1])), 1, torch.tensor([0, 1]))
print(a21)
# 第三行最后一个
a33 = torch.index_select(torch.index_select(A, 0, torch.tensor([2])), 1, torch.tensor([2]))
print(a33)
a21.shape

tensor([[4]])
tensor([[3, 9]])
tensor([[4]])


torch.Size([1, 2])

In [34]:
A = torch.tensor([[4,5,7]])
A.shape

torch.Size([1, 3])